FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bot-service ./bot-service/cmd/main.go

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /bot-service /bot-service
ENTRYPOINT ["/bot-service"]
